when:
  - event: tag

steps:
  - name: publish_image
    image: woodpeckerci/plugin-kaniko
    settings:
      registry: ghcr.io
      repo: ${CI_REPO}
      username:
        from_secret: ghcr_username
      password:
        from_secret: ghcr_token
      tags: ${CI_COMMIT_TAG}

  - name: discord success notification
    image: appleboy/drone-discord
    environment: 
      DRONE_BUILD_FINISHED: ${CI_STEP_STARTED}
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        ✅ Repository `[{{repo.name}}/{{commit.branch}}]` triggered by event `[{{uppercase build.event}}]` for build.

        - Commit [[{{commit.sha}}]({{commit.link}})]
        - Author `[{{commit.author}} / {{commit.email}}]`
        - Message: {{commit.message}}
        - Woodpecker build [[#{{build.number}}]({{build.link}})] reported `[SUCCESS]` at <t:{{build.finished}}:f>

    depends_on: [publish_image]
    when:
      status: [success]

  - name: discord failed notification
    image: appleboy/drone-discord
    environment: 
      DRONE_BUILD_FINISHED: ${CI_STEP_STARTED}
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
      message: >
        ❌ Repository `[{{repo.name}}/{{commit.branch}}]` triggered by event `[{{uppercase build.event}}]` for build.

        - Commit [[{{commit.sha}}]({{commit.link}})]
        - Author `[{{commit.author}} / {{commit.email}}]`
        - Message: {{commit.message}}
        - Woodpecker build [[#{{build.number}}]({{build.link}})] reported `[FAILED]` at {{build.finished}}

    depends_on: [publish_image]
    when:
      status: [failure]
